## Data + Coordinate plane + Geometrical object + Mapping of data onto plane (what's x, what's y) + Extras

# Load data 
source(here::here("data/day3_objects.R"))

# Gapminder 07
filter(gapminder, year==2007)

# Basic Scatter Plot
ggplot(data = gapminder07) +
    geom_point(mapping=aes(x=gdpPercap, y=lifeExp)) +
    labs(title="Relationship between Life Expectancy and GDP per Capita in 2007", x="GDP per Capita", y="Life Expectancy")

# Log Relationship
gapminder07$log_pop <- log(gapminder07$pop)
gapminder07$log_gdpPercap <- log(gapminder07$gdpPercap)
ggplot(data = gapminder07) +
    theme_bw() +
    geom_point(mapping=aes(x=log_gdpPercap, y=log_pop)) +
    labs(title="Log Relationship between Population and GDP per Capita in 2007", x="GDP per Capita", y="Population")
## alternatively write directly into ggplot code
ggplot(gapminder07) +
    theme_bw() +
    geom_point(aes(x=log(pop), y=log(gdpPercap)))

# Energy Generated over Time
long_gen %>% 
    group_by(datetime) %>% 
    summarise(output=sum(output)) %>% 
    ggplot() +
    theme_bw() + 
    geom_col(aes(x=datetime, y=output)) + 
    labs(title="Total energy generated, by hour", x="Hour", y="Output (MW)")

# Hydro power generated over time
long_gen %>% 
    group_by(datetime) %>%
    filter(source == "large_hydro" | source == "small_hydro") %>% 
    summarise(output=sum(output)) %>% 
    ggplot() +
    theme_bw() +
    geom_col(aes(x=datetime, y=output)) + 
    labs(titles = "Total Hydroelectric power generated, by hour", x="Hour", y= "Output (MW)")
## alternatively filter
filter(source %in% c("large_hydro", "small_hydro"))
filter(str_detect(source,"hydro"))

# Line Plots
imports %>% 
    ggplot() +
    theme_bw() +
    geom_line(aes(x=datetime, y=imports), size=.8, col="red") +
    labs(title="Energy imports over time", x="Hour", y="Amount imported (MW)")

# Box Plots
long_gen %>% 
    ggplot() +
    theme_bw() +
    geom_boxplot(aes(x=source, y=output)) +
    labs(title="Amount of energy generated by each source, Sept 3-9", x="Source type", y="Output (MW)")

# Smoother and 95% CIs
generation %>% 
    ggplot() +
    geom_line(aes(x=datetime, y=large_hydro), col="turquoise3") +
    geom_smooth(aes(x=datetime, y=large_hydro)) +
    labs(title="Hydroelectric (large) generation per hour, Sept 3-9", x="Hydro", y="Output (MW)")

# Total Output per source
long_merged_energy %>% 
    group_by(source) %>% 
    summarise(output=sum(output)) %>% 
    ggplot() +
    theme_bw() +
    geom_col(aes(x=source, y=output), col="darkred") + 
    geom_hline(aes(yintercept =(mean(output)))) +
    labs(titles = "Total Output per Source", x="Source", y= "Output (MW)")
    
# Imports over Time
imports %>% 
    ggplot() +
    theme_minimal() +
    geom_line(aes(x=datetime, y=imports), col="red") +
    scale_x_datetime(date_labels="%H:%M", date_breaks = "12 hours") +
    labs(title="Energy imports over time in California", subtitle="Hourly data from Sept 3-9, 2018")

# Colors and fill
long_merged_energy %>% 
    ggplot() +
    theme_bw() +
    geom_line(aes(x=datetime, y=output, group=source, col=source)) +
    labs(title="Output by energy source over time", subtitle="Hourly data from Sept 3-9, 2018", x="Hour", y="Output (MW)")

long_merged_energy %>% 
    group_by(source) %>% 
    filter(source == "wind" | source == "solar" | source == "geothermal") %>% 
    ggplot() +
    theme_bw() +
    geom_line(aes(x=datetime, y=output, group=source, col=source), size=1.5) +
    scale_color_brewer(palette="Accent", name="Energy source") +
    labs(title="Wind vs Solar vs Geothermal generation", x="Hour", y="Output (MW)", subtitle="Hourly data from Sept 3-9, 2018")
